(cl:in-package inertial-msg)
(cl:export '(HEADER-VAL
          HEADER
          TIME-VAL
          TIME
          ACCELERATIONX-VAL
          ACCELERATIONX
          ACCELERATIONY-VAL
          ACCELERATIONY
          ACCELERATIONZ-VAL
          ACCELERATIONZ
          ANGULARRATEX-VAL
          ANGULARRATEX
          ANGULARRATEY-VAL
          ANGULARRATEY
          ANGULARRATEZ-VAL
          ANGULARRATEZ
          NAVSTATUS-VAL
          NAVSTATUS
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
          VELOCITYNORTH-VAL
          VELOCITYNORTH
          VELOCITYEAST-VAL
          VELOCITYEAST
          VELOCITYDOWN-VAL
          VELOCITYDOWN
          HEADING-VAL
          HEADING
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
))