/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /program/catkin_ws/src/ugv/lms511_1/msg/Lms1Status.msg
 *
 */


#ifndef LMS511_1_MESSAGE_LMS1STATUS_H
#define LMS511_1_MESSAGE_LMS1STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace lms511_1
{
template <class ContainerAllocator>
struct Lms1Status_
{
  typedef Lms1Status_<ContainerAllocator> Type;

  Lms1Status_()
    : header()
    , nLms1Status(0)
    , timeLms1()  {
    }
  Lms1Status_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , nLms1Status(0)
    , timeLms1()  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _nLms1Status_type;
  _nLms1Status_type nLms1Status;

   typedef ros::Time _timeLms1_type;
  _timeLms1_type timeLms1;




  typedef boost::shared_ptr< ::lms511_1::Lms1Status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lms511_1::Lms1Status_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct Lms1Status_

typedef ::lms511_1::Lms1Status_<std::allocator<void> > Lms1Status;

typedef boost::shared_ptr< ::lms511_1::Lms1Status > Lms1StatusPtr;
typedef boost::shared_ptr< ::lms511_1::Lms1Status const> Lms1StatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lms511_1::Lms1Status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lms511_1::Lms1Status_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lms511_1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'lms511_1': ['/program/catkin_ws/src/ugv/lms511_1/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lms511_1::Lms1Status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lms511_1::Lms1Status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lms511_1::Lms1Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lms511_1::Lms1Status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lms511_1::Lms1Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lms511_1::Lms1Status_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lms511_1::Lms1Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ebc6c9f19b9743c8a2c77db17cb6677b";
  }

  static const char* value(const ::lms511_1::Lms1Status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xebc6c9f19b9743c8ULL;
  static const uint64_t static_value2 = 0xa2c77db17cb6677bULL;
};

template<class ContainerAllocator>
struct DataType< ::lms511_1::Lms1Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lms511_1/Lms1Status";
  }

  static const char* value(const ::lms511_1::Lms1Status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lms511_1::Lms1Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
#Lms1 status\n\
uint8 nLms1Status\n\
#Lms1 time stamp\n\
time timeLms1\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const ::lms511_1::Lms1Status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lms511_1::Lms1Status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.nLms1Status);
      stream.next(m.timeLms1);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Lms1Status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lms511_1::Lms1Status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lms511_1::Lms1Status_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "nLms1Status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.nLms1Status);
    s << indent << "timeLms1: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timeLms1);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LMS511_1_MESSAGE_LMS1STATUS_H
