/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /program/catkin_ws/src/ugv/velodyne0/msg/VerticalMeasurements.msg
 *
 */


#ifndef VELODYNE0_MESSAGE_VERTICALMEASUREMENTS_H
#define VELODYNE0_MESSAGE_VERTICALMEASUREMENTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace velodyne0
{
template <class ContainerAllocator>
struct VerticalMeasurements_
{
  typedef VerticalMeasurements_<ContainerAllocator> Type;

  VerticalMeasurements_()
    : header()
    , horizontal_angle(0.0)
    , vertical_angle()
    , dist()
    , intensity()
    , x()
    , y()
    , z()  {
    }
  VerticalMeasurements_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , horizontal_angle(0.0)
    , vertical_angle(_alloc)
    , dist(_alloc)
    , intensity(_alloc)
    , x(_alloc)
    , y(_alloc)
    , z(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _horizontal_angle_type;
  _horizontal_angle_type horizontal_angle;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _vertical_angle_type;
  _vertical_angle_type vertical_angle;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _dist_type;
  _dist_type dist;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _intensity_type;
  _intensity_type intensity;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _x_type;
  _x_type x;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _y_type;
  _y_type y;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _z_type;
  _z_type z;




  typedef boost::shared_ptr< ::velodyne0::VerticalMeasurements_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::velodyne0::VerticalMeasurements_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct VerticalMeasurements_

typedef ::velodyne0::VerticalMeasurements_<std::allocator<void> > VerticalMeasurements;

typedef boost::shared_ptr< ::velodyne0::VerticalMeasurements > VerticalMeasurementsPtr;
typedef boost::shared_ptr< ::velodyne0::VerticalMeasurements const> VerticalMeasurementsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::velodyne0::VerticalMeasurements_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::velodyne0::VerticalMeasurements_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace velodyne0

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'velodyne0': ['/program/catkin_ws/src/ugv/velodyne0/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::velodyne0::VerticalMeasurements_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::velodyne0::VerticalMeasurements_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::velodyne0::VerticalMeasurements_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::velodyne0::VerticalMeasurements_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::velodyne0::VerticalMeasurements_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::velodyne0::VerticalMeasurements_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::velodyne0::VerticalMeasurements_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f296aa88cbdbdca9ac3ee669b94aa4a3";
  }

  static const char* value(const ::velodyne0::VerticalMeasurements_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf296aa88cbdbdca9ULL;
  static const uint64_t static_value2 = 0xac3ee669b94aa4a3ULL;
};

template<class ContainerAllocator>
struct DataType< ::velodyne0::VerticalMeasurements_<ContainerAllocator> >
{
  static const char* value()
  {
    return "velodyne0/VerticalMeasurements";
  }

  static const char* value(const ::velodyne0::VerticalMeasurements_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::velodyne0::VerticalMeasurements_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 horizontal_angle\n\
float32[] vertical_angle\n\
float32[] dist\n\
float32[] intensity\n\
float32[] x\n\
float32[] y\n\
float32[] z\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::velodyne0::VerticalMeasurements_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::velodyne0::VerticalMeasurements_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.horizontal_angle);
      stream.next(m.vertical_angle);
      stream.next(m.dist);
      stream.next(m.intensity);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct VerticalMeasurements_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::velodyne0::VerticalMeasurements_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::velodyne0::VerticalMeasurements_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "horizontal_angle: ";
    Printer<float>::stream(s, indent + "  ", v.horizontal_angle);
    s << indent << "vertical_angle[]" << std::endl;
    for (size_t i = 0; i < v.vertical_angle.size(); ++i)
    {
      s << indent << "  vertical_angle[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.vertical_angle[i]);
    }
    s << indent << "dist[]" << std::endl;
    for (size_t i = 0; i < v.dist.size(); ++i)
    {
      s << indent << "  dist[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.dist[i]);
    }
    s << indent << "intensity[]" << std::endl;
    for (size_t i = 0; i < v.intensity.size(); ++i)
    {
      s << indent << "  intensity[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.intensity[i]);
    }
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.y[i]);
    }
    s << indent << "z[]" << std::endl;
    for (size_t i = 0; i < v.z.size(); ++i)
    {
      s << indent << "  z[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.z[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VELODYNE0_MESSAGE_VERTICALMEASUREMENTS_H
