(cl:in-package transformation-msg)
(cl:export '(HEADER-VAL
          HEADER
          ACCELERATIONX-VAL
          ACCELERATIONX
          ACCELERATIONY-VAL
          ACCELERATIONY
          ACCELERATIONZ-VAL
          ACCELERATIONZ
          ANGULARRATEX-VAL
          ANGULARRATEX
          ANGULARRATEY-VAL
          ANGULARRATEY
          ANGULARRATEZ-VAL
          ANGULARRATEZ
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
          VELOCITYX-VAL
          VELOCITYX
          VELOCITYY-VAL
          VELOCITYY
          VELOCITYZ-VAL
          VELOCITYZ
          HEADING-VAL
          HEADING
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
))